### ISSUE TITLE
DeFi wallet login buton breaks the Next.js build

### ISSUE THREAD

**Issue by VladimirAndrianov96** [multiversx/mx-sdk-dapp#1046]
I always get this
```
ReferenceError: navigator is not defined
    at y (**\.next\server\chunks\2335.js:23:102029)
    at nM (**\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:47419)
    at nN (**\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:64674)
    at nI (**\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:46806)
    at nM (**\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:47570)
    at nN (**\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:64674)
    at nB (**\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:67657)
    at nF (**\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:66824)
    at nN (**\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:64990)
    at nB (**\node_modules\next\dist\compiled\next-server\app-page.runtime.prod.js:12:67657)
```

when I uncomment the following component at the `/unlock` page

```              
              <ExtensionLoginButton
                onLoginRedirect={onLoginRedirect}
                loginButtonText="DeFi Wallet"
                {...commonProps}
              />
```

**Comment by VladimirAndrianov96** [comment]
Other components work as expected, probably this is related to me missing some of wrappers at the code or this should work as expected if all other options work fine?

```
              <WalletConnectLoginButton
                loginButtonText="xPortal App"
                onLoginRedirect={onLoginRedirect}
                {...commonProps}
              />
              <LedgerLoginButton
                loginButtonText="Ledger"
                onLoginRedirect={onLoginRedirect}
                {...commonProps}
              />
               Comment this out as this breaks the build due to errors inside
              <ExtensionLoginButton
                onLoginRedirect={onLoginRedirect}
                loginButtonText="DeFi Wallet"
                {...commonProps}
              />
              <OperaWalletLoginButton
                loginButtonText="Opera Crypto Wallet - Beta"
                {...commonProps}
              />
              <WebWalletLoginButton
                loginButtonText="Web Wallet"
                data-testid="webWalletLoginBtn"
                {...commonProps}
              />
              ```

**Comment by VladimirAndrianov96** [comment]
I have moved this Next.js-related issue to Next.js repository
https://github.com/multiversx/mx-template-dapp-nextjs/issues/52
