### ISSUE TITLE
How to send a NFT to an endpoint

### ISSUE THREAD

**Issue by alexisdavidson** [multiversx/mx-sdk-dapp#712]
I've been trying to follow the tutorial https://docs.multiversx.com/sdk-and-tools/sdk-js/sdk-js-cookbook/#single-nft-transfer but first of all it's deprecated, and also it doesn't show any way to send a NFT to an endpoint of a smart contract.

Any idea how I can do so?

My current code is:

```
let payload = new ESDTNFTTransferPayloadBuilder()
            .setPayment(payment)
            .setDestination(new Address(smartContractAddress))
            .build();
        
        const transaction = {
            value: 0,
            data: payload,
            receiver: account.address,
            gasLimit: '60000000'
        };
```

**Comment by bogdan-rosianu** [comment]
Hello! 
As mentioned [here](https://github.com/multiversx/mx-sdk-js-core/blob/main/src/tokenTransferBuilders.ts#L34), that section is deprecated. You should use [this](https://github.com/multiversx/mx-sdk-js-core/blob/main/src/transactionFactory.ts#L103) instead. 

The cookbook will be updated with the next sdk-js-core's releases. 
Thanks !

**Comment by alexisdavidson** [comment]
Can you please provide an example as to how to use this? I could not find any

**Comment by bogdan-rosianu** [comment]
You can see some examples in the test file:
- https://github.com/multiversx/mx-sdk-js-core/blob/bc45a7a15ab6bdd98e2f5c486814992a5e5e87bc/src/transactionFactory.spec.ts#L52
- https://github.com/multiversx/mx-sdk-js-core/blob/bc45a7a15ab6bdd98e2f5c486814992a5e5e87bc/src/transactionFactory.spec.ts#L68

**Comment by alexisdavidson** [comment]
Thanks, it doesn't look that the tokens get sent to a specific endpoints in these examples.
My goal is to send an NFT to the endpoint of a smart contract so that a function is triggered and the token received as payment

**Comment by alexisdavidson** [comment]
Thanks for these. I'm currently trying out to build an interaction but I received the following error when trying to trigger it:

`Uncaught (in promise) TypeError: value.bech32 is not a function
    at new AddressValue (address.ts:26:1)
    at TokenTransfersWithinInteraction.getTypedTokensReceiver (interaction.ts:284:1)
    at TokenTransfersWithinInteraction.buildArgsForSingleESDTNFTTransfer (interaction.ts:234:1)
    at Interaction.buildTransaction (interaction.ts:101:1)
    at sendSpendTicketTransaction (Lottery.js:211:1)
    at spendTicket (Lottery.js:49:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)` 


Here is my current code:

        const tokenCollection = "LTICKET-5a5231"
        const tokenNonce = 1
        let payment = TokenPayment.nonFungible(tokenCollection, tokenNonce);

        let contract = new SmartContract({ address: lotteryContractAddress });
        let buyTicketFunction = new ContractFunction("buy_ticket");
        let args = [];
        let interaction = new Interaction(contract, buyTicketFunction, args);
        console.log(interaction.withSingleESDTNFTTransfer(payment));
        
        let tx = interaction
            .withNonce(7)
            .withValue(payment)
            .withGasLimit(20000000)
            .withChainID("D")
            .buildTransaction();

**Comment by CiprianDraghici** [comment]
Probably you missed to set the sender address:

eg. 
```
 let tx = interaction
        .withNonce(7)
        .withValue(payment)
        .withGasLimit(20000000)
        .withChainID("D")
        
        .withSender(Address.fromString("erd......")
        
        .buildTransaction();
```
